package android_serialport_api.xingbang.db.greenDao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import android_serialport_api.xingbang.db.QuYu;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "QuYu".
*/
public class QuYuDao extends AbstractDao<QuYu, Long> {

    public static final String TABLENAME = "QuYu";

    /**
     * Properties of entity QuYu.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "id");
        public final static Property Qyid = new Property(1, int.class, "qyid", false, "qyid");
        public final static Property Name = new Property(2, String.class, "name", false, "name");
        public final static Property Sum = new Property(3, String.class, "sum", false, "sum");
        public final static Property DelayMin = new Property(4, String.class, "delayMin", false, "delayMin");
        public final static Property DelayMax = new Property(5, String.class, "delayMax", false, "delayMax");
        public final static Property Shouquan = new Property(6, String.class, "shouquan", false, "shouquan");
        public final static Property StartDelay = new Property(7, String.class, "startDelay", false, "startDelay");
        public final static Property KongDelay = new Property(8, String.class, "kongDelay", false, "kongDelay");
        public final static Property PaiDelay = new Property(9, String.class, "paiDelay", false, "paiDelay");
    }


    public QuYuDao(DaoConfig config) {
        super(config);
    }
    
    public QuYuDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"QuYu\" (" + //
                "\"id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"qyid\" INTEGER NOT NULL ," + // 1: qyid
                "\"name\" TEXT," + // 2: name
                "\"sum\" TEXT," + // 3: sum
                "\"delayMin\" TEXT," + // 4: delayMin
                "\"delayMax\" TEXT," + // 5: delayMax
                "\"shouquan\" TEXT," + // 6: shouquan
                "\"startDelay\" TEXT," + // 7: startDelay
                "\"kongDelay\" TEXT," + // 8: kongDelay
                "\"paiDelay\" TEXT);"); // 9: paiDelay
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"QuYu\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, QuYu entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getQyid());
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
 
        String sum = entity.getSum();
        if (sum != null) {
            stmt.bindString(4, sum);
        }
 
        String delayMin = entity.getDelayMin();
        if (delayMin != null) {
            stmt.bindString(5, delayMin);
        }
 
        String delayMax = entity.getDelayMax();
        if (delayMax != null) {
            stmt.bindString(6, delayMax);
        }
 
        String shouquan = entity.getShouquan();
        if (shouquan != null) {
            stmt.bindString(7, shouquan);
        }
 
        String startDelay = entity.getStartDelay();
        if (startDelay != null) {
            stmt.bindString(8, startDelay);
        }
 
        String kongDelay = entity.getKongDelay();
        if (kongDelay != null) {
            stmt.bindString(9, kongDelay);
        }
 
        String paiDelay = entity.getPaiDelay();
        if (paiDelay != null) {
            stmt.bindString(10, paiDelay);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, QuYu entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getQyid());
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
 
        String sum = entity.getSum();
        if (sum != null) {
            stmt.bindString(4, sum);
        }
 
        String delayMin = entity.getDelayMin();
        if (delayMin != null) {
            stmt.bindString(5, delayMin);
        }
 
        String delayMax = entity.getDelayMax();
        if (delayMax != null) {
            stmt.bindString(6, delayMax);
        }
 
        String shouquan = entity.getShouquan();
        if (shouquan != null) {
            stmt.bindString(7, shouquan);
        }
 
        String startDelay = entity.getStartDelay();
        if (startDelay != null) {
            stmt.bindString(8, startDelay);
        }
 
        String kongDelay = entity.getKongDelay();
        if (kongDelay != null) {
            stmt.bindString(9, kongDelay);
        }
 
        String paiDelay = entity.getPaiDelay();
        if (paiDelay != null) {
            stmt.bindString(10, paiDelay);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public QuYu readEntity(Cursor cursor, int offset) {
        QuYu entity = new QuYu( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // qyid
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // name
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // sum
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // delayMin
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // delayMax
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // shouquan
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // startDelay
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // kongDelay
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9) // paiDelay
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, QuYu entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setQyid(cursor.getInt(offset + 1));
        entity.setName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setSum(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setDelayMin(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setDelayMax(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setShouquan(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setStartDelay(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setKongDelay(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setPaiDelay(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(QuYu entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(QuYu entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(QuYu entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
