package android_serialport_api.mx.xingbang.db.greenDao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import android_serialport_api.mx.xingbang.db.DenatorHis_Main_all;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "denatorHis_Main_all".
*/
public class DenatorHis_Main_allDao extends AbstractDao<DenatorHis_Main_all, Long> {

    public static final String TABLENAME = "denatorHis_Main_all";

    /**
     * Properties of entity DenatorHis_Main_all.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "id");
        public final static Property Blastdate = new Property(1, String.class, "blastdate", false, "blastdate");
        public final static Property UploadStatus = new Property(2, String.class, "uploadStatus", false, "uploadStatus");
        public final static Property Longitude = new Property(3, String.class, "longitude", false, "longitude");
        public final static Property Latitude = new Property(4, String.class, "latitude", false, "latitude");
        public final static Property Userid = new Property(5, String.class, "userid", false, "userid");
        public final static Property FiredNo = new Property(6, String.class, "firedNo", false, "firedNo");
        public final static Property SerialNo = new Property(7, int.class, "serialNo", false, "serialNo");
        public final static Property ContactNo = new Property(8, String.class, "contactNo", false, "contactNo");
        public final static Property ProjectNo = new Property(9, String.class, "projectNo", false, "projectNo");
        public final static Property Remark = new Property(10, String.class, "remark", false, "remark");
    }


    public DenatorHis_Main_allDao(DaoConfig config) {
        super(config);
    }
    
    public DenatorHis_Main_allDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"denatorHis_Main_all\" (" + //
                "\"id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"blastdate\" TEXT," + // 1: blastdate
                "\"uploadStatus\" TEXT," + // 2: uploadStatus
                "\"longitude\" TEXT," + // 3: longitude
                "\"latitude\" TEXT," + // 4: latitude
                "\"userid\" TEXT," + // 5: userid
                "\"firedNo\" TEXT," + // 6: firedNo
                "\"serialNo\" INTEGER NOT NULL ," + // 7: serialNo
                "\"contactNo\" TEXT," + // 8: contactNo
                "\"projectNo\" TEXT," + // 9: projectNo
                "\"remark\" TEXT);"); // 10: remark
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"denatorHis_Main_all\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, DenatorHis_Main_all entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String blastdate = entity.getBlastdate();
        if (blastdate != null) {
            stmt.bindString(2, blastdate);
        }
 
        String uploadStatus = entity.getUploadStatus();
        if (uploadStatus != null) {
            stmt.bindString(3, uploadStatus);
        }
 
        String longitude = entity.getLongitude();
        if (longitude != null) {
            stmt.bindString(4, longitude);
        }
 
        String latitude = entity.getLatitude();
        if (latitude != null) {
            stmt.bindString(5, latitude);
        }
 
        String userid = entity.getUserid();
        if (userid != null) {
            stmt.bindString(6, userid);
        }
 
        String firedNo = entity.getFiredNo();
        if (firedNo != null) {
            stmt.bindString(7, firedNo);
        }
        stmt.bindLong(8, entity.getSerialNo());
 
        String contactNo = entity.getContactNo();
        if (contactNo != null) {
            stmt.bindString(9, contactNo);
        }
 
        String projectNo = entity.getProjectNo();
        if (projectNo != null) {
            stmt.bindString(10, projectNo);
        }
 
        String remark = entity.getRemark();
        if (remark != null) {
            stmt.bindString(11, remark);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, DenatorHis_Main_all entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String blastdate = entity.getBlastdate();
        if (blastdate != null) {
            stmt.bindString(2, blastdate);
        }
 
        String uploadStatus = entity.getUploadStatus();
        if (uploadStatus != null) {
            stmt.bindString(3, uploadStatus);
        }
 
        String longitude = entity.getLongitude();
        if (longitude != null) {
            stmt.bindString(4, longitude);
        }
 
        String latitude = entity.getLatitude();
        if (latitude != null) {
            stmt.bindString(5, latitude);
        }
 
        String userid = entity.getUserid();
        if (userid != null) {
            stmt.bindString(6, userid);
        }
 
        String firedNo = entity.getFiredNo();
        if (firedNo != null) {
            stmt.bindString(7, firedNo);
        }
        stmt.bindLong(8, entity.getSerialNo());
 
        String contactNo = entity.getContactNo();
        if (contactNo != null) {
            stmt.bindString(9, contactNo);
        }
 
        String projectNo = entity.getProjectNo();
        if (projectNo != null) {
            stmt.bindString(10, projectNo);
        }
 
        String remark = entity.getRemark();
        if (remark != null) {
            stmt.bindString(11, remark);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public DenatorHis_Main_all readEntity(Cursor cursor, int offset) {
        DenatorHis_Main_all entity = new DenatorHis_Main_all( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // blastdate
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // uploadStatus
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // longitude
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // latitude
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // userid
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // firedNo
            cursor.getInt(offset + 7), // serialNo
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // contactNo
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // projectNo
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10) // remark
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, DenatorHis_Main_all entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setBlastdate(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setUploadStatus(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setLongitude(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setLatitude(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setUserid(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setFiredNo(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setSerialNo(cursor.getInt(offset + 7));
        entity.setContactNo(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setProjectNo(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setRemark(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(DenatorHis_Main_all entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(DenatorHis_Main_all entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(DenatorHis_Main_all entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
