package android_serialport_api.mx.xingbang.db.greenDao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import android_serialport_api.mx.xingbang.db.Temporary_database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "Temporary_database".
*/
public class Temporary_databaseDao extends AbstractDao<Temporary_database, Long> {

    public static final String TABLENAME = "Temporary_database";

    /**
     * Properties of entity Temporary_database.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "id");
        public final static Property DenatorId = new Property(1, String.class, "denatorId", false, "denatorId");
        public final static Property ShellBlastNo = new Property(2, String.class, "shellBlastNo", false, "shellBlastNo");
    }


    public Temporary_databaseDao(DaoConfig config) {
        super(config);
    }
    
    public Temporary_databaseDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"Temporary_database\" (" + //
                "\"id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"denatorId\" TEXT," + // 1: denatorId
                "\"shellBlastNo\" TEXT);"); // 2: shellBlastNo
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"Temporary_database\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Temporary_database entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String denatorId = entity.getDenatorId();
        if (denatorId != null) {
            stmt.bindString(2, denatorId);
        }
 
        String shellBlastNo = entity.getShellBlastNo();
        if (shellBlastNo != null) {
            stmt.bindString(3, shellBlastNo);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Temporary_database entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String denatorId = entity.getDenatorId();
        if (denatorId != null) {
            stmt.bindString(2, denatorId);
        }
 
        String shellBlastNo = entity.getShellBlastNo();
        if (shellBlastNo != null) {
            stmt.bindString(3, shellBlastNo);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Temporary_database readEntity(Cursor cursor, int offset) {
        Temporary_database entity = new Temporary_database( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // denatorId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // shellBlastNo
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Temporary_database entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setDenatorId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setShellBlastNo(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Temporary_database entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Temporary_database entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Temporary_database entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
