package android_serialport_api.mx.xingbang.db.greenDao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import android_serialport_api.mx.xingbang.db.UserMain;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "UserMain".
*/
public class UserMainDao extends AbstractDao<UserMain, Long> {

    public static final String TABLENAME = "UserMain";

    /**
     * Properties of entity UserMain.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "id");
        public final static Property Uname = new Property(1, String.class, "uname", false, "uname");
        public final static Property Upassword = new Property(2, String.class, "upassword", false, "upassword");
        public final static Property Isface = new Property(3, String.class, "isface", false, "isface");
        public final static Property Facepath = new Property(4, String.class, "facepath", false, "facepath");
    }


    public UserMainDao(DaoConfig config) {
        super(config);
    }
    
    public UserMainDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"UserMain\" (" + //
                "\"id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"uname\" TEXT," + // 1: uname
                "\"upassword\" TEXT," + // 2: upassword
                "\"isface\" TEXT," + // 3: isface
                "\"facepath\" TEXT);"); // 4: facepath
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"UserMain\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, UserMain entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String uname = entity.getUname();
        if (uname != null) {
            stmt.bindString(2, uname);
        }
 
        String upassword = entity.getUpassword();
        if (upassword != null) {
            stmt.bindString(3, upassword);
        }
 
        String isface = entity.getIsface();
        if (isface != null) {
            stmt.bindString(4, isface);
        }
 
        String facepath = entity.getFacepath();
        if (facepath != null) {
            stmt.bindString(5, facepath);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, UserMain entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String uname = entity.getUname();
        if (uname != null) {
            stmt.bindString(2, uname);
        }
 
        String upassword = entity.getUpassword();
        if (upassword != null) {
            stmt.bindString(3, upassword);
        }
 
        String isface = entity.getIsface();
        if (isface != null) {
            stmt.bindString(4, isface);
        }
 
        String facepath = entity.getFacepath();
        if (facepath != null) {
            stmt.bindString(5, facepath);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public UserMain readEntity(Cursor cursor, int offset) {
        UserMain entity = new UserMain( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // uname
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // upassword
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // isface
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4) // facepath
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, UserMain entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUname(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setUpassword(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setIsface(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setFacepath(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(UserMain entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(UserMain entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(UserMain entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
